name: Build and Pack

on: [push, pull_request]

jobs:
  #########################################################################################
  ## Build the documentation using mkdoc
  ## It will be pushed to the gh-pages branch
  #########################################################################################
  build-documentation:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
      - run: |
          pip install --upgrade pip && pip install mkdocs mkdocs-gen-files mkdocs-awesome-pages-plugin
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Publish docs
        run: |
          mkdocs gh-deploy
