###########################################################################################
# Build the documentation using mkdocs
# This will update the gh-pages branch which in return triggers the pages-build-deployment
# Action (provided by Github, not editable)
# That action will publish it to https://jomjol.github.io/AI-on-the-edge-device-docs
###########################################################################################

name: Build Documentation

on: 
  push:
    branches:
    - main

jobs:
  build-documentation:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Cache PIP
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
          
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
      - run: |
          pip install --upgrade pip && pip install mkdocs mkdocs-gen-files mkdocs-awesome-pages-plugin mkdocs-material mkdocs-enumerate-headings-plugin
          git config user.name 'li_yi_bing'
          git config user.email 'li_yi_bing@outlook.com'
          
      - name: Generate Parameter Page
        run: |
          cd param-docs
          # Fetch the parameter pages from the main repo
          git clone https://github.com/li-yibing/esp32-edge-computing-docs.git
          python concat-parameter-pages.py
        
      - name: Store Documentation in the gh-pages branch so it gets pushed to the website
        run: mkdocs gh-deploy
